global:
  slack_api_url: 'https://hooks.slack.com/services/fake/fake/fake'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#yuriy_semenkov'
