version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ../src/ui
    image: ${USER_NAME}/ui:${VERSION_UI:-2.0}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USER_NAME}/post:${VERSION_POST:-1.0}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    build: ../src/comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USER_NAME}/comment:${VERSION_COMMENT:-1.0}
    networks:
      - back_net
      - front_net

volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.0.1.0/24"
