version: '3.3'
services:

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - back_net
      - front_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - back_net
      - front_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'


  mongo-exporter:
    image: elarasu/mongodb_exporter@sha256:6d58466a866b25cff5fd19617790d188ebba2474af9e02bb8accb85b5147b69b
    environment:
      - MONGODB_URL=mongodb://post_db:27017
    networks:
      - back_net
      - front_net

  cloudprober:
    image: cloudprober/cloudprober:v0.10.9
    environment:
      - CLOUDPROBER_HOST=0.0.0.0
    volumes:
      - ./cloudprober.cfg:/etc/cloudprober.cfg
    ports:
      - '9313:9313'
    networks:
      - back_net
      - front_net

  cadvisor:
    image: google/cadvisor:v0.29.0
    networks:
        - back_net
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADM_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADM_PASSWORD}
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - back_net
  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - back_net


volumes:
    prometheus_data:
    grafana_data:

networks:
    back_net:
    front_net:
